### PR TITLE
feat: Add custom trigger for coin rooms

### LINKED ISSUE #163: [Request] Add functionality for bw key coin rooms
Not sure how this would exactly be handled but a few suggestions were to have the key coins activated if you enter a specified entrance or add a hole with a one-way to prevent cheese

### PR DESCRIPTION
**Pull request by Jeremy-Vidaurri**
Adds a custom trigger that automatically activates all switches in a room. This closes #163

### CODE REVIEW

**Comment by rhelmot** [comment]
Should the trigger RemoveSelf() on activation?

**Comment by Jeremy-Vidaurri** [comment]
Would the trigger reappear when you enter the room? If not, then no since the switches reset on transition

**Comment by Jeremy-Vidaurri** [comment]
Okay, looking at it. RemoveSelf() isn't necessary as activating the trigger more than once doesn't do anything, but it also doesn't hurt to add it. Your call really.

**Comment by rhelmot** [comment]
sounds good to meeeeeeeeeeeee

**Pull request merged**
